"""retailsense_contracts - the frozen shared vocabulary of RetailSense (v1.0.0).

Import the module you need (``from retailsense_contracts.events import Event``)
or the flat re-exports below (``from retailsense_contracts import Event``).
Sub-modules:

    enums       closed vocabularies (EventClass, AlertKind, ShelfState, ...)
    ids/hlc     ULIDs and the hybrid logical clock
    clock       Clock protocol, SystemClock, SimClock, store-day helpers
    geometry    pure-numpy polygons, lines (normative crossing rule), IoU
    events      Event envelope, Observation, all payloads (discriminated union)
    alerts      Alert, ImpactInr, per-kind details, ACTIONS_BY_KIND
    impact      THE rupee formula (lost_sales / recovered / queue_abandon_risk)
    config      StoreConfig (store.yaml) + load/dump
    api / ws    REST and WebSocket models
    topics      MQTT topics + outbox expiry policy
    db          SQLAlchemy Core DDL for edge and cloud, insert_ignore, sqlite_engine
    manifest    OTA ModelManifest + assigned_version rule
    i18n        Hindi/English templates, render(), fmt_inr()
    interfaces  every Protocol + hot-path dataclasses
    registry    resolve(key) with fake fallback
    testing     deterministic fakes and sample builders
    synthetic   palette/geometry constants shared by sim and CV
    privacy     RetentionPolicy, PrivacyManifest
    settings    env var names + defaults
    logging     JSON logger factory (UTF-8 safe on Windows)
"""

from .version import VERSION  # noqa: I001  (must come first: sub-modules import it)

from . import (
    alerts,
    api,
    clock,
    config,
    db,
    enums,
    events,
    geometry,
    hlc,
    i18n,
    ids,
    impact,
    interfaces,
    manifest,
    privacy,
    registry,
    settings,
    synthetic,
    testing,
    topics,
    ws,
)
from .alerts import (
    ACTIONS_BY_KIND,
    Alert,
    AlertAckRequest,
    AlertDetails,
    CameraAlertDetails,
    DeviceAlertDetails,
    FootfallAlertDetails,
    ImpactInr,
    QueueAlertDetails,
    ShrinkAlertDetails,
    StockoutAlert,
    SyncAlertDetails,
)
from .api import (
    ChainRank,
    ChainRankRow,
    ChaosRequest,
    Command,
    DailyReport,
    DailySummary,
    DeliveryReceipt,
    DeviceStatus,
    ErrorResponse,
    FitReport,
    FleetView,
    FootfallForecast,
    FootfallForecastDay,
    HealthStatus,
    HeatCell,
    HeatmapResponse,
    IngestAck,
    IngestBatch,
    IntegrationsStatus,
    KpiDaily,
    KpiRange,
    KpiToday,
    LinkRequest,
    ManifestPublishRequest,
    ModelStatus,
    OndcAck,
    OndcPublishRequest,
    OutboundMessage,
    QueueView,
    ReconcileReport,
    ReconcileRow,
    ReorderSuggestion,
    RolloutRequest,
    ScenarioRequest,
    ScenarioStatus,
    Series,
    SeriesPoint,
    ShelfStateView,
    ShelvesUpdate,
    SkuEnrolResponse,
    Store,
    SyncStatus,
    WhatsAppReply,
    ZonesUpdate,
)
from .clock import Clock, FrozenClock, SimClock, SystemClock, day_start_ts, store_date
from .config import (
    SKU,
    CameraConfig,
    Counter,
    DemoConfig,
    DeviceConfig,
    Floorplan,
    HomographyConfig,
    IntegrationsConfig,
    Line,
    MqttConfig,
    OndcConfig,
    PrivacyConfig,
    RulesConfig,
    ShelfPolygon,
    ShelfReference,
    StoreConfig,
    StoreInfo,
    TallyConfig,
    UplinkConfig,
    WhatsAppConfig,
    Zone,
    dump_store_config,
    load_store_config,
)
from .enums import (
    AckAction,
    AckBy,
    AlertKind,
    AlertStatus,
    Anchor,
    DetectorKind,
    Direction,
    EventClass,
    Lang,
    LineKind,
    LinkState,
    Origin,
    Severity,
    ShelfState,
    UplinkMode,
    ZoneKind,
)
from .events import (
    EVENT_CLASS,
    EVENT_TYPES,
    PAYLOAD_CLASSES,
    AlertAcked,
    AlertRaised,
    AlertResolved,
    CameraHealth,
    ConfigApplied,
    DeviceHeartbeat,
    DwellSample,
    Event,
    EventType,
    FootfallCrossing,
    HeatmapTile,
    HeatmapTiles,
    Observation,
    OrderRequested,
    Payload,
    QueueForecast,
    QueueSnapshot,
    ShelfScan,
    ShelfStateChange,
    SimTruth,
    StockReconciled,
    ZoneOccupancy,
    make_event,
)
from .geometry import (
    bbox_polygon_overlap,
    iou,
    point_in_polygon,
    polygon_area,
    polygon_bbox,
    polygon_long_axis,
    segments_intersect,
    side_of_line,
)
from .hlc import HLC
from .i18n import TEMPLATES, fmt_inr, render
from .ids import new_ulid
from .impact import ImpactConfig, lost_sales, queue_abandon_risk, rate_per_hour, recovered
from .interfaces import (
    AnalyticsUpdate,
    CloudFootfallForecaster,
    CloudQueueForecaster,
    CoverageEstimator,
    CoverageResult,
    Crossing,
    Detection,
    Detector,
    EdgeQueueForecaster,
    EdgeStore,
    ErpClient,
    Frame,
    FrameSource,
    LinkController,
    Notifier,
    OndcPublisher,
    PointMapper,
    QueueAnalyzer,
    RuleEngine,
    ShelfStateMachine,
    SkuIdentifier,
    SourceError,
    SyntheticControl,
    Track,
    Tracker,
    Uplink,
    ZoneEngine,
)
from .logging import get_logger
from .manifest import ModelEntry, ModelIO, ModelManifest, RolloutPolicy, assigned_version
from .privacy import PrivacyManifest, RetentionPolicy
from .registry import FAKES, IMPLEMENTATIONS, Unavailable, is_real, resolve
from .synthetic import SyntheticPalette
from .topics import EVICTABLE, EXPIRY_S, cmd_topic, status_topic, topic
from .ws import WsKind, WsMessage

# Resolve any forward references now that every module is loaded.
for _m in (
    AlertRaised,
    AlertResolved,
    ShelfStateChange,
    Observation,
    Event,
    IngestBatch,
    ModelStatus,
    ManifestPublishRequest,
    Store,
    DailyReport,
):
    _m.model_rebuild()

__all__ = [
    "ACTIONS_BY_KIND",
    "EVENT_CLASS",
    "EVENT_TYPES",
    "EVICTABLE",
    "EXPIRY_S",
    "FAKES",
    "HLC",
    "IMPLEMENTATIONS",
    "PAYLOAD_CLASSES",
    "SKU",
    "TEMPLATES",
    "VERSION",
    "AckAction",
    "AckBy",
    "Alert",
    "AlertAckRequest",
    "AlertAcked",
    "AlertDetails",
    "AlertKind",
    "AlertRaised",
    "AlertResolved",
    "AlertStatus",
    "AnalyticsUpdate",
    "Anchor",
    "CameraAlertDetails",
    "CameraConfig",
    "CameraHealth",
    "ChainRank",
    "ChainRankRow",
    "ChaosRequest",
    "Clock",
    "CloudFootfallForecaster",
    "CloudQueueForecaster",
    "Command",
    "ConfigApplied",
    "Counter",
    "CoverageEstimator",
    "CoverageResult",
    "Crossing",
    "DailyReport",
    "DailySummary",
    "DeliveryReceipt",
    "DemoConfig",
    "Detection",
    "Detector",
    "DetectorKind",
    "DeviceAlertDetails",
    "DeviceConfig",
    "DeviceHeartbeat",
    "DeviceStatus",
    "Direction",
    "DwellSample",
    "EdgeQueueForecaster",
    "EdgeStore",
    "ErpClient",
    "ErrorResponse",
    "Event",
    "EventClass",
    "EventType",
    "FitReport",
    "FleetView",
    "Floorplan",
    "FootfallAlertDetails",
    "FootfallCrossing",
    "FootfallForecast",
    "FootfallForecastDay",
    "Frame",
    "FrameSource",
    "FrozenClock",
    "HealthStatus",
    "HeatCell",
    "HeatmapResponse",
    "HeatmapTile",
    "HeatmapTiles",
    "HomographyConfig",
    "ImpactConfig",
    "ImpactInr",
    "IngestAck",
    "IngestBatch",
    "IntegrationsConfig",
    "IntegrationsStatus",
    "KpiDaily",
    "KpiRange",
    "KpiToday",
    "Lang",
    "Line",
    "LineKind",
    "LinkController",
    "LinkRequest",
    "LinkState",
    "ManifestPublishRequest",
    "ModelEntry",
    "ModelIO",
    "ModelManifest",
    "ModelStatus",
    "MqttConfig",
    "Notifier",
    "Observation",
    "OndcAck",
    "OndcConfig",
    "OndcPublishRequest",
    "OndcPublisher",
    "OrderRequested",
    "Origin",
    "OutboundMessage",
    "Payload",
    "PointMapper",
    "PrivacyConfig",
    "PrivacyManifest",
    "QueueAlertDetails",
    "QueueAnalyzer",
    "QueueForecast",
    "QueueSnapshot",
    "QueueView",
    "ReconcileReport",
    "ReconcileRow",
    "ReorderSuggestion",
    "RetentionPolicy",
    "RolloutPolicy",
    "RolloutRequest",
    "RuleEngine",
    "RulesConfig",
    "ScenarioRequest",
    "ScenarioStatus",
    "Series",
    "SeriesPoint",
    "Severity",
    "ShelfPolygon",
    "ShelfReference",
    "ShelfScan",
    "ShelfState",
    "ShelfStateChange",
    "ShelfStateMachine",
    "ShelfStateView",
    "ShelvesUpdate",
    "ShrinkAlertDetails",
    "SimClock",
    "SimTruth",
    "SkuEnrolResponse",
    "SkuIdentifier",
    "SourceError",
    "StockReconciled",
    "StockoutAlert",
    "Store",
    "StoreConfig",
    "StoreInfo",
    "SyncAlertDetails",
    "SyncStatus",
    "SyntheticControl",
    "SyntheticPalette",
    "SystemClock",
    "TallyConfig",
    "Track",
    "Tracker",
    "Unavailable",
    "Uplink",
    "UplinkConfig",
    "UplinkMode",
    "WhatsAppConfig",
    "WhatsAppReply",
    "WsKind",
    "WsMessage",
    "Zone",
    "ZoneEngine",
    "ZoneKind",
    "ZoneOccupancy",
    "ZonesUpdate",
    "alerts",
    "api",
    "assigned_version",
    "bbox_polygon_overlap",
    "clock",
    "cmd_topic",
    "config",
    "day_start_ts",
    "db",
    "dump_store_config",
    "enums",
    "events",
    "fmt_inr",
    "geometry",
    "get_logger",
    "hlc",
    "i18n",
    "ids",
    "impact",
    "interfaces",
    "iou",
    "is_real",
    "load_store_config",
    "lost_sales",
    "make_event",
    "manifest",
    "new_ulid",
    "point_in_polygon",
    "polygon_area",
    "polygon_bbox",
    "polygon_long_axis",
    "privacy",
    "queue_abandon_risk",
    "rate_per_hour",
    "recovered",
    "registry",
    "render",
    "resolve",
    "segments_intersect",
    "settings",
    "side_of_line",
    "status_topic",
    "store_date",
    "synthetic",
    "testing",
    "topic",
    "topics",
    "ws",
]
